plugins {
    id 'latest-wrapper'
    id 'java-conventions'
    id 'application'
    id 'co.uzzu.dotenv.gradle' version '4.0.0'
}

dependencies {
    implementation 'com.nulab-inc:backlog4j:2.7.0'
    runtimeOnly 'org.slf4j:slf4j-jdk14:2.0.17'
}

application {
    mainClass.set('org.mtzky.backlog.wiki.Rename')
}

run {
    environment << env.allVariables()
    systemProperty 'user.language', 'en'
    systemProperty 'user.country', 'US'
    systemProperty 'java.util.logging.config.file', file('src/conf/logging.properties')
}

tasks.withType(Test).configureEach {
    environment << env.allVariables()
    systemProperty 'user.language', 'en'
    systemProperty 'user.country', 'US'
    systemProperty 'java.util.logging.config.file', file('src/conf/logging-test.properties')
}
